# Generated by Django 5.1 on 2025-05-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('decription', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('unit', models.CharField(max_length=100)),
                ('image', models.BinaryField()),
                ('id_restaurant', models.CharField(max_length=100)),
                ('is_delected', models.BooleanField(default=None, null=True)),
            ],
            options={
                'db_table': 'dish',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DishCart',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('id_dish', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=None, null=True)),
                ('note', models.CharField(default=None, max_length=100, null=True)),
                ('is_checked', models.BooleanField()),
            ],
            options={
                'db_table': 'dish_cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DishInvoice',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('id_dish_cart', models.CharField(max_length=100)),
                ('id_invoice', models.CharField(default=None, max_length=100, null=True)),
                ('id_customer', models.CharField(max_length=100)),
                ('id_rate', models.CharField(default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'dish_invoice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('id_restaurant', models.CharField(default=None, max_length=100, null=True)),
                ('time', models.DateTimeField(default=None, null=True)),
                ('status', models.IntegerField(default=None, null=True)),
                ('total_payment', models.IntegerField(default=None, null=True)),
                ('shipping_fee', models.IntegerField(default=None, null=True)),
                ('id_deleted', models.BooleanField(default=None, null=True)),
            ],
            options={
                'db_table': 'invoice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('comment', models.CharField(default=None, max_length=100, null=True)),
                ('star', models.IntegerField()),
            ],
            options={
                'db_table': 'rate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=100, null=True)),
                ('decription', models.CharField(default=None, max_length=500, null=True)),
                ('street', models.CharField(default=None, max_length=100, null=True)),
                ('district', models.CharField(default=None, max_length=100, null=True)),
                ('image', models.BinaryField(default=None, null=True)),
                ('is_deleted', models.BooleanField()),
            ],
            options={
                'db_table': 'restaurant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('role', models.IntegerField()),
                ('street', models.CharField(default=None, max_length=100, null=True)),
                ('district', models.CharField(default=None, max_length=100, null=True)),
                ('is_deleted', models.BooleanField()),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
