# Generated by Django 5.1 on 2025-05-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRestaurant',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('id_user', models.CharField(max_length=100)),
                ('id_restaurant', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user_restaurant',
                'managed': False,
            },
        ),
    ]

