from django.urls import path
from . import views
from . import view2

urlpatterns = [
    path('customer-home/', views.customer_home, name='customer-home'),
    path('dish-detail/', views.dish_detail, name='dish-detail'),
    path('restaurant-view-details/', views.restaurant_view_details, name='restaurant-view-details'),
    path('cart/', views.cart, name='cart'),
    path('shippingOrder/', view2.shipping_orders_view_no_customer_id, name='shipping-orders'),
    path('shippingOrderNoCustomerId/', view2.shipping_orders_view_no_customer_id, name='shipping-orders-no-customer-id'),
    path('order-history/', views.order_history, name='order-history'),
    path('api/submit-rating/', views.api_submit_rating, name='api-submit-rating'),
    path('spending-statistics/', views.spending_statistics, name='spending-statistics'),
    path('change-password/', views.change_password, name='change-password'),
    path('login/', views.login, name='login'),
    path('', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('customer-info/', views.customer_info, name='customer-info'),
    path('restaurant-owner-home/', views.restaurant_owner_home, name='restaurant-owner-home'),
    path('restaurant-pending-order/', views.pending_orders_view, name='pending-orders'),
    path('restaurant-pending-order/confirm/<str:invoice_id>/', views.confirm_pending_order, name='confirm-pending-order'),
    path('restaurant-pending-order/reject/<str:invoice_id>/', views.reject_pending_order, name='reject-pending-order'),
    path('restaurant-shipping-order/', views.restaurant_shipping_order, name='restaurant-shipping-order'),
    path('restaurant-shipping-orders/', views.shipping_orders_view, name='restaurant-shipping-orders'),
    path('restaurant-order-history/', views.restaurant_order_history, name='restaurant-order-history'),
    path('revenue-statistics/', views.revenue_statistics, name='revenue-statistics'),
    path('logout/', views.logout, name='logout'),
    path('restaurant-info/', views.restaurant_info, name='restaurant-info'),
    path('restaurant-owner-info/', views.restaurant_owner_info, name='restaurant-owner-info'),
    path('restaurant-owner-change-password/', views.restaurant_owner_change_password, name='restaurant-owner-change-password'),
    path('api/add-dish/', views.api_add_dish, name='api-add-dish'),
    path('api/update-dish/', views.api_update_dish, name='api-update-dish'),
    path('api/delete-dish/', views.api_delete_dish, name='api-delete-dish'),
    path('api/dish-reviews/', views.api_dish_reviews, name='api-dish-reviews'),
    path('api/update-invoice-status/', views.api_update_invoice_status, name='api-update-invoice-status'),
    path('restaurants/', views.restaurant_list, name='restaurant-list'),
    path('api/delete-cart-item/', views.api_delete_cart_item, name='api-delete-cart-item'),
    path('api/add-to-cart/', views.api_add_to_cart, name='api-add-to-cart'),
    path('api/create-invoice/', views.api_create_invoice, name='api-create-invoice'),
    path('api/confirm-payment/', views.api_confirm_payment, name='api-confirm-payment'),
]

